# Generated by Django 3.2.13 on 2024-03-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostsByUser', '0003_auto_20240301_0348'),
    ]

    operations = [
    ]
