# Generated by Django 3.2.13 on 2024-03-01 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PostsByUser', '0004_auto_20240301_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image_description', models.CharField(max_length=600)),
                ('image_tagged_topics', models.CharField(max_length=200)),
                ('image_Post', models.ImageField(upload_to='posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='PostsByUser.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Pin_Creation',
        ),
    ]
