# Generated by Django 3.2.13 on 2024-03-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_auto_20240228_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='userimages/'),
        ),
    ]
